[package]
name = "ez_jni"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "1.0.0"
either = "1.13.0"
jni = { version = "0.21", default-features = false }
jni_macros = { path = "./jni_macros" }

