name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '21'
    - name: Build
      run: rustup target add x86_64-linux-android && cargo build --target x86_64-linux-android --verbose
    - name: Run tests
      run: cargo test -p ez_jni -p ez_jni_macros --verbose
