name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'oracle'
        java-version: '21'
    - name: Build
      run: rustup target add x86_64-linux-android && cargo build --target x86_64-linux-android --verbose
    - name: Run tests
      run: cargo test -p ez_jni -p ez_jni_macros --verbose

  # doc:
  #   name: Build Documentation
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Install Doc dependencies
  #       run: cargo install cargo-deadlinks
  #     - name: Build Documentation
  #       run: cargo doc && cargo deadlinks --check-http
